version: "3.2"

services:
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./static/:/usr/share/nginx/html/

  tiles:
    image: klokantech/openmaptiles-server
    volumes:
      - ./data:/data
